# Generated by Django 4.1.9 on 2023-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField(auto_now_add=True)),
                ("affair", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
            ],
        ),
    ]
