# Generated by Django 4.1.9 on 2023-06-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("estados", "0001_initial"),
        ("tematicas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_hour", models.TimeField(blank=True)),
                ("day", models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("location_length", models.CharField(blank=True, default=0, max_length=200)),
                ("location_width", models.CharField(blank=True, default=0, max_length=200)),
                ("capacity", models.IntegerField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True)),
                ("images", models.ImageField(upload_to="imagenes")),
                ("hours_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ubicaciones.hours")),
                ("state_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="estados.state")),
                ("theme_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tematicas.theme")),
            ],
        ),
    ]
