# Generated by Django 4.1.9 on 2023-06-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("servicios", "0001_initial"),
        ("ubicaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("estimated_price", models.IntegerField(blank=True)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=50)),
                ("size", models.IntegerField(default=3)),
                ("date_event", models.DateField(blank=True)),
                ("service_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="servicios.service")),
                (
                    "ubication_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ubicaciones.location"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("total_price", models.IntegerField()),
                ("final_date", models.DateField(blank=True)),
                ("quote_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cotizacion.quote")),
            ],
        ),
    ]
